console.log(Math.floor(1.4));
console.log(Math.ceil(1.4));
console.log(Math.abs(-1));
console.log(Math.sin(2));
console.log(Math.cos(2));
console.log(Math.random());
console.log(Math.random() * 5);
console.log((Math.random() * 5 ) + 10 );
console.log(Math.max(1, 3, 5, 11));
console.log(Math.min(1, 3, 5, 11));
console.log(Math.round(1.4));
console.log(Math.pow(2, 2));